version: '3.8'

services:
  vue-dev:
    image: node:18-alpine
    container_name: vue-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8003:80"
    command: sh -c "npm install && npm run serve"
    environment:
      - HOST=0.0.0.0
    restart: unless-stopped
